import { AntdRegistry } from '@ant-design/nextjs-registry';
import '../styles/fonts.css';
import "./globals.css";


export const metadata = {
  title: "Prime Holiday Destinations",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={` antialiased bg-[#fffff0]`}
      >
    
    <AntdRegistry>{children}</AntdRegistry>
   
      </body>
    </html>
  );
}
