import '../styles/fonts.css';
import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import Footer from "./components/shared/Footer";
import Navbar from "./components/shared/Navbar";
import ScrollTopButton from "./components/shared/ScrollTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prime Holiday Destinations",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        <ScrollTopButton />
      </body>
    </html>
  );
}
