
import Footer from "../components/shared/Footer";
import Navbar from "../components/shared/Navbar";
import ScrollTopButton from "../components/shared/ScrollTopButton";


export const metadata = {
  title: "Prime Holiday Destinations",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 
      <div
        className={` antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        <ScrollTopButton />
      </div>
 
  );
}
